services:
  - type: web
    name: nirvant-site
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Nirvant.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nirvant-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    healthCheckPath: /